services:
    rpi_imagegen:
        build: .
        privileged: true
        stdin_open: true
        tty: true
        image: rpi-imagegen:latest
        volumes:
            - ./uniclogs:/home/imagegen/uniclogs
        #     - ./out:/home/imagegen/rpi-image-gen/work
