services:
    rpi_imagegen:
        build: 
            context: .
            dockerfile: docker/Dockerfile
        privileged: true
        stdin_open: true
        tty: true
        image: rpi-imagegen:latest
        working_dir: /home/imagegen/rpi-image-gen
        volumes:
            - ./uniclogs:/home/imagegen/uniclogs
